name: fluttercartoon
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_easyrefresh: ^2.1.1 #刷新
  flutter_swiper: ^1.1.6 #轮播图
  fluttertoast: ^3.1.3
  flutter_redux: ^0.6.0
  share: ^0.6.2+5
  flutter_spinkit: ^4.1.1+1
  sqflite: ^1.2.0
  pub_semver: ^1.4.2
  flutter_svg: ^0.17.0
  flutter_slidable: ^0.5.4
  dio: ^3.0.7
  event_bus:  ^1.1.0
  flutter_cache_manager: ^1.1.3
  path_provider: ^1.5.1
  permission_handler: 3.2.2
  scoped_model: ^1.0.1
  #  flutter_webview_plugin: 0.3.10+1
  #  webview_flutter: ^0.3.21
  bezier: ^1.1.2
  provider: ^4.0.0
  flare_flutter: ^1.8.3
#   固定版本
  json_annotation: 3.0.1 #json注释
  json_serializable: ^3.3.0 #json序列化


  package_info: 0.4.0+13
  connectivity: 0.4.6+1
  flutter_markdown: 0.3.3
  rxdart: 0.22.3
  device_info: 0.4.1+4
  url_launcher: 5.4.1
  google_fonts: 0.3.9
  android_intent: 0.3.4+8
#  shared_preferences: 0.5.7
#  built_value: 7.1.0
  graphql: 2.1.0
  flutter_json_widget: 1.0.2
  simple_animations: 1.3.4
  flutter_localizations:
    sdk: flutter
  photo_view:
    git:
      url: https://github.com/CarSmallGuo/photo_view.git
      ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter
    # 配合使用命令：flutter packages pub run build_runner build
    # 配合使用命令：flutter packages pub run build_runner watch
  build_runner: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/common/nodata@2x.png
    - assets/images/common/normal_placeholder_h@2x.png
    - assets/images/common/normal_placeholder_v@2x.png
    - assets/images/common/rank_frist@2x.png
    - assets/images/common/rank_second@2x.png
    - assets/images/common/rank_third@2x.png
    - assets/images/common/yaofan@2x.png

    - assets/images/mine/mine_accout@2x.png
    - assets/images/mine/mine_author@2x.png
    - assets/images/mine/mine_bg_for_boy@2x.png
    - assets/images/mine/mine_bg_for_girl@2x.png
    - assets/images/mine/mine_cashew@2x.png
    - assets/images/mine/mine_coin@2x.png
    - assets/images/mine/mine_feedBack@2x.png
    - assets/images/mine/mine_freed@2x.png
    - assets/images/mine/mine_judge@2x.png
    - assets/images/mine/mine_mail@2x.png
    - assets/images/mine/mine_message@2x.png
    - assets/images/mine/mine_seal@2x.png
    - assets/images/mine/mine_setting@2x.png
    - assets/images/mine/mine_subscript@2x.png
    - assets/images/mine/mine_vip@2x.png

    - assets/images/navigation/nav_back_black@2x.png
    - assets/images/navigation/nav_back_white@2x.png
    - assets/images/navigation/nav_bg@2x.png
    - assets/images/navigation/nav_reload@2x.png
    - assets/images/navigation/nav_search@2x.png

    - assets/images/read/readerMenu_catalog@2x.png
    - assets/images/read/readerMenu_changeScreen_vertical@2x.png
    - assets/images/read/readerMenu_changeScreen_horizontal@2x.png
    - assets/images/read/readerMenu_luminance@2x.png

    - assets/images/recommend/gender_female@2x.png
    - assets/images/recommend/gender_male@2x.png
    - assets/images/refresh/refresh_discover@2x.png
    - assets/images/refresh/refresh_kiss@2x.png
    - assets/images/refresh/refresh_loading_1@2x.png
    - assets/images/refresh/refresh_loading_2@2x.png
    - assets/images/refresh/refresh_loading_3@2x.png
    - assets/images/refresh/refresh_normal@2x.png
    - assets/images/refresh/refresh_will_refresh@2x.png

    - assets/images/search/search_history_delete@2x.png
    - assets/images/search/search_keyword_refresh@2x.png
    - assets/images/tab/tab_book@2x.png
    - assets/images/tab/tab_book_S@2x.png
    - assets/images/tab/tab_class@2x.png
    - assets/images/tab/tab_class_S@2x.png
    - assets/images/tab/tab_home@2x.png
    - assets/images/tab/tab_home_S@2x.png
    - assets/images/tab/tab_mine@2x.png
    - assets/images/tab/tab_mine_S@2x.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
